language: csharp
mono: none
dotnet: 3.1.202
script:
 - dotnet restore
 - dotnet build
 - bash publish.sh
 
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "build/ndig.exe"
  skip_cleanup: true
  on:
    tags: true 